# Generated by Django 4.1 on 2022-08-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_journal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='picture',
        ),
    ]
