# Generated by Django 4.1 on 2022-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_remove_journal_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
