# Generated by Django 4.1 on 2022-08-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_journal_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='favorite',
        ),
    ]
